baseURL = "https://machinelearning.sg/"
languageCode = "en-us"
title = "Machine Learning SG"
theme = "ml-sg"
paginate = 20
googleAnalytics = "UA-185405110-2"

[params]
recent_posts_number = 6
description = "machinelearning.sg is a ground-up effort to build, grow and celebrate the machine learning community in Singapore. It also aims to be a place to feature and discuss research and trends in artificial intelligence and machine learning."

[menu]
    [[menu.main]]
        identifier = "research"
        title = "Research"
        url = "/research"
        weight = 1
    [[menu.main]]
        identifier = "researcher"
        title = "Researchers"
        url = "/researcher"
        parent = "research"
        weight = 2
    [[menu.main]]
        identifier = "publication"
        title = "Publications"
        url = "/publication"
        parent = "research"
        weight = 3
    [[menu.main]]
        identifier = "institution"
        title = "Institutions"
        url = "/institution"
        parent = "research"
        weight = 4
    [[menu.main]]
        identifier = "code"
        title = "Code"
        url = "/code"
        weight = 2
    [[menu.main]]
        identifier = "coder"
        title = "Coders"
        url = "/coder"
        parent = "code"
        weight = 2
    [[menu.main]]
        identifier = "repo"
        title = "Repos"
        url = "/repo"
        parent = "code"
        weight = 3
    [[menu.main]]
        identifier = "jobs"
        title = "Jobs"
        url = "/jobs"
        weight = 3
    [[menu.main]]
        identifier = "news"
        title = "News"
        url = "https://news.machinelearning.sg/"
        weight = 4
    [[menu.research]]
        identifier = "research-overview"
        title = "Research"
        url = "/research/"
        weight = 1
    [[menu.research]]
        identifier = "research-researcher"
        title = "Researchers"
        url = "/researcher"
        name = "researcher"
        weight = 2
    [[menu.research]]
        identifier = "research-publication"
        title = "Publications"
        url = "/publication"
        name = "publication"
        weight = 3
    [[menu.research]]
        identifier = "research-institution"
        title = "Institutions"
        url = "/institution"
        name = "institution"
        weight = 4
    [[menu.code]]
        identifier = "code-overview"
        title = "Code"
        url = "/code"
        weight = 1
    [[menu.code]]
        identifier = "code-coder"
        title = "Coders"
        url = "/coder"
        name = "coder"
        weight = 2
    [[menu.code]]
        identifier = "code-repo"
        title = "Repos"
        url = "/repo"
        name = "repo"
        weight = 3


